name: Builder

on:
  push:
    paths:
      - 'source/**'
      - index.php.src
      - .github/workflows/build.yml
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cp index.php index.orig.php && php build/builder.php
      - name: Check Changes
        id: change
        run: (diff index.php index.orig.php && echo "changed=false" >> "$GITHUB_OUTPUT") || echo "changed=true" >> "$GITHUB_OUTPUT"
      - name: Commit & Push
        if: steps.change.outputs.changed == 'true'
        run: |
         git config --global user.name 'Hints Builder'
         git config --global user.email 'internet@limelightgaming.net'
         git add "index.php"
         git commit -m "Updated index.php"
         git push
